# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: LooraMoora
email: hello@looramoora.com
description: > # this means to ignore newlines until "baseurl:"
  Laura Morelli - Product Designer.
  I’m passionate about human interaction and reactions using digital products.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://looramoora.com" # the base hostname & protocol for your site
twitter_username: looramoora
github_username:  looramoora

# Outputting
permalink: /:categories/:title
timezone: Europe/Rome

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed
